name: Linters

on: pull_request

env:
  FORCE_COLOR: 1

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Setup ESLint
        run: |
          npm install --save-dev eslint@7.17.x eslint-config-airbnb@18.2.x eslint-plugin-prettier@7.1.x eslint-plugin-jsx-a11y@6.4.x 
          eslint-plugin-prettier@3.3.x
          prettier@2.2.x 
          @typescript-eslint/eslint-plugin@4.12.x @typescript-eslint/parsers@4.12.x
          [ -f .eslintrc] || wget https://github.com/FlowFintech/FlowFront/blob/release/.eslintrc
      - name: ESLint Report
        run: npx eslint .
